### ISSUE TITLE
Schema is missing when querying DATABASECHANGELOGLOCK existence

### ISSUE THREAD

**Issue by Ra13s** [syjer/liquibaseorausertable#1]
The schema name seems to be missing from the DBMetadata.hasTableNamed method. 
This causes the DATABASECHANGELOGLOCK table to be tried to be recreated.
https://github.com/syjer/liquibaseorausertable/blob/main/src/main/java/ch/digitalfondue/liquibaseorausertable/DBMetadata.java#L109

I tried the following query, this seems to work for me.
"SELECT CASE WHEN EXISTS (SELECT * FROM all_tables WHERE owner = '" + database.getDefaultSchemaName() + "' AND upper(table_name) = upper('" + tableName + "')) THEN 1 ELSE 0 END FROM dual");

**Comment by syjer** [comment]
hi @Ra13s , the goal of this library is to avoid touching the `ALL_*` tables, so I can't really use your query.

As you have noticed, all the queries will go to the `USER_*` tables, so it may be possible that this library will not cover all use cases (like using a different user for executing the migration and the connection for the application (?)).

**Comment by Ra13s** [comment]
Yes, I figured the user_* tables were probably chosen for that purpose.
However, I didn't really notice any slowdowns just with querying the lock or log table from the all_* tables with around 3000 tables.
Anyway, good work with the lib, I think I might just fork this and customize it for our needs.

**Comment by syjer** [comment]
>However, I didn't really notice any slowdowns just with querying the lock or log table from the all_* tables with around 3000 tables.

I'll do a test on our DB, if there is no slowdown, I can try to integrate your query and offer a configuration switch.

**Comment by syjer** [comment]
Ok, with 9600 tables it's not slow.  20ms for the query.

I'll try to integrate your query with a configuration switch.

But I wonder if in your case only this query need to be changed (?)

**Comment by Ra13s** [comment]
Great! I didn't notice any other problems when running it, the other queries also looked as if they had schema or catalog names specified.

**Comment by syjer** [comment]
@Ra13s  thanks for the feedback, I'll do an update to the library + release as soon as I can :)

**Comment by syjer** [comment]
hi @Ra13s , if it's ok for you that a system property (`-Dorausertable.hasTableNamedQueryInAll=true`) (see https://github.com/syjer/liquibaseorausertable/pull/2/files#diff-cf5fb4e542897c2ebf1a600d1a908ae70f6a2490b54398956b4e32b11e5a6539R37 ) can configure the query, I'll merge the PR and make a release :).

**Comment by Ra13s** [comment]
hi, I think it's good 👍, should work fine for me.

**Comment by syjer** [comment]
ok, I'll do a release tomorrow! Thank you :)

**Comment by syjer** [comment]
@Ra13s I've releasead the version 1.9 : https://search.maven.org/artifact/ch.digitalfondue.liquibaseorausertable/liquibaseorausertable/1.9/jar . 
I'll update the README this afternoon :).
