### ISSUE TITLE
Make liquibaseorausertable compatible with Liquibase 4.23.0+

### ISSUE THREAD

**Issue by PascalSchumacher** [syjer/liquibaseorausertable#4]
Liquibase `4.23.0` changed the `ChangeLogHistoryService`, see the `Breaking Changes` section of https://github.com/liquibase/liquibase/releases/tag/v4.23.0 and https://github.com/liquibase/liquibase/pull/4310

Therefore `liquibaseorausertable` has to be adapted to make it work with Liquibase `4.23.0`.

By the way: Thank you very much for providing this project! 👍

**Comment by syjer** [comment]
hi @PascalSchumacher thank you for the tip. I'll have a look at what it would mean to update and add some kind of compatiblity with the new version.

If the changes required are too big, I'll most likely not update the project, as currently I'm fortunate enough to not interact with an Oracle db. (Or maybe I will need to find a smarter way to rewrite the queries, but unfortunately the USER_ and ALL_ tables are quite differents, so it's not only a search and replace ;( )
